import MarketStatus from "./components/HomeComponents/MarketStatus";
import PopularStocks from "./components/HomeComponents/PopularStocks/PopularStocks";
import NavBar from "./components/NavBar";
import "./globals.css";
import { Poppins } from "next/font/google";

const poppins = Poppins({
  weight: ["400", "500", "700"],
  subsets: ["latin-ext"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html>
      <body className={`bg-white  ${poppins.className}`}>
        <NavBar />
        <div className="max-w-6xl m-auto pt-28">
          <MarketStatus />
          <PopularStocks />
          {children}
        </div>
      </body>
    </html>
  );
}
