export const metadata = {
  title: "Article",
  description: "Generated by create next app",
};

export default function ArticleLayout({
  children,
}: {
  children: React.ReactNode;
  params: {
    title: string;
  };
}) {
  return <div className="w-full h-screen max-w-6xl m-auto">{children}</div>;
}
